# -*- coding: utf-8 -*-
"""MemeKanseriTahmini.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DTJ0QAf1FSDAZ-WQ-Se0mlc1CJ1CjRNE
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

dfC = pd.read_excel("memeKanresi.xlsx")

df = dfC.copy()

df.head(3)

df.tail(3)

df.shape

df.info()

df.describe().T

df.median()

df.isnull().any()

plt.figure(figsize= (16,6))
plt.subplot(1,3,1)
sns.boxplot(x= "Class", y= "Clump Thickness", data = df, color = 'red')

plt.subplot(1,3,2)
sns.boxplot(x= "Class", y="Uniformity of Cell Size", data = df, color = 'green')

plt.subplot(1,3,3)
sns.boxplot(x= "Class", y= "Single Epithelial Cell Size", data= df, color = 'pink')

plt.show()

plt.figure(figsize= (16,6))
plt.subplot(1,3,1)
sns.distplot(df['Class'])

plt.subplot(1,3,2)
sns.distplot(df['Bare Nuclei'], color = 'green')

plt.subplot(1,3,3)
sns.distplot(df['Mitoses'], color = 'red')

plt.show()

df.hist(bins = 23, figsize=(35,35), layout=(7,4), color='skyblue')

corr = df.corr()

print(corr)

plt.figure(figsize= (17,6))
sns.heatmap(corr, annot = True, fmt = ".2f", linewidths=0.3 , linecolor="blue", cmap="rocket_r")
plt.show()

plt.figure(figsize= (17,6))
plt.subplot(2, 2, 1)
sns.lineplot(x="Class", y="Clump Thickness", data=df)

plt.subplot(2, 2, 2)
sns.lineplot(x="Class", y="Uniformity of Cell Size", data=df, color='red')

plt.subplot(2, 2, 3)
sns.lineplot(x="Class", y="Uniformity of Cell Shape", data=df, color='green')

plt.subplot(2, 2, 4)
sns.lineplot(x="Class", y="Bare Nuclei", color='yellow', data=df)

plt.show()

sns.pairplot(df, hue='Class', palette='coolwarm')
plt.show()

plt.figure(figsize=(12, 6))
sns.violinplot(x='Class', y='Bare Nuclei', data=df, palette='Set2')
plt.show()

plt.figure(figsize=(14, 8))
sns.swarmplot(x='Class', y='Single Epithelial Cell Size', data=df, palette='Set2')
plt.show()

plt.figure(figsize=(10, 6))
sns.barplot(x='Class', y='Mitoses', data=df, palette='Set2')
plt.show()

